let data = [{
        "id": 1,
        "name": "Trouser one",
        "price": 500,
        "color": "blue",
        "type": "bottom wear",
        "category": "men",
        "subCategory": "casual trousers",
        "image": "men/Bottom wear/casual trousers/trouser1.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 2,
        "name": "Trouser two",
        "price": 700,
        "color": "blue",
        "type": "bottom wear",
        "category": "men",
        "subCategory": "casual trousers",
        "image": "men/Bottom wear/casual trousers/trouser2.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 3,
        "name": "Trouser three",
        "price": 900,
        "color": "blue",
        "type": "bottom wear",
        "category": "men",
        "subCategory": "casual trousers",
        "image": "men/Bottom wear/casual trousers/trouser3.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 4,
        "name": "Trouser four",
        "price": 600,
        "color": "blue",
        "type": "bottom wear",
        "category": "men",
        "subCategory": "casual trousers",
        "image": "men/Bottom wear/casual trousers/trouser4.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 5,
        "name": "Trouser five",
        "price": 800,
        "color": "blue",
        "type": "bottom wear",
        "category": "men",
        "subCategory": "casual trousers",
        "image": "men/Bottom wear/casual trousers/trouser5.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 6,
        "name": "Formal one",
        "price": 500,
        "color": "grey",
        "type": "bottom wear",
        "category": "men",
        "subCategory": "formal trousers",
        "image": "men/Bottom wear/formal trousers/formal1.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 7,
        "name": "Formal two",
        "price": 700,
        "color": "grey",
        "type": "bottom wear",
        "category": "men",
        "subCategory": "formal trousers",
        "image": "men/Bottom wear/formal trousers/formal2.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 8,
        "name": "Formal three",
        "price": 900,
        "color": "grey",
        "type": "bottom wear",
        "category": "men",
        "subCategory": "formal trousers",
        "image": "men/Bottom wear/formal trousers/formal3.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 9,
        "name": "Formal four",
        "price": 600,
        "color": "grey",
        "type": "bottom wear",
        "category": "men",
        "subCategory": "formal trousers",
        "image": "men/Bottom wear/formal trousers/formal4.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 10,
        "name": "Formal five",
        "price": 800,
        "color": "grey",
        "type": "bottom wear",
        "category": "men",
        "subCategory": "formal trousers",
        "image": "men/Bottom wear/formal trousers/formal5.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 11,
        "name": "Jeans one",
        "price": 1000,
        "color": "black",
        "type": "bottom wear",
        "category": "men",
        "subCategory": "jeans",
        "image": "men/Bottom wear/jeans/jeans1.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 12,
        "name": "Jeans two",
        "price": 1200,
        "color": "black",
        "type": "bottom wear",
        "category": "men",
        "subCategory": "jeans",
        "image": "men/Bottom wear/jeans/jeans2.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 13,
        "name": "Jeans three",
        "price": 1400,
        "color": "black",
        "type": "bottom wear",
        "category": "men",
        "subCategory": "jeans",
        "image": "men/Bottom wear/jeans/jeans3.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 14,
        "name": "Jeans four",
        "price": 1100,
        "color": "black",
        "type": "bottom wear",
        "category": "men",
        "subCategory": "jeans",
        "image": "men/Bottom wear/jeans/jeans4.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 15,
        "name": "Jeans five",
        "price": 1600,
        "color": "black",
        "type": "bottom wear",
        "category": "men",
        "subCategory": "jeans",
        "image": "men/Bottom wear/jeans/jeans5.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 16,
        "name": "kurta one",
        "price": 1300,
        "color": "green",
        "type": "kurta & festive wear",
        "category": "men",
        "subCategory": "kurta set",
        "image": "men/Kurta & festive wear/kurta set/kurta1.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 17,
        "name": "kurta two",
        "price": 1000,
        "color": "green",
        "type": "kurta & festive wear",
        "category": "men",
        "subCategory": "kurta set",
        "image": "men/Kurta & festive wear/kurta set/kurta2.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 18,
        "name": "kurta three",
        "price": 1900,
        "color": "green",
        "type": "kurta & festive wear",
        "category": "men",
        "subCategory": "kurta set",
        "image": "men/Kurta & festive wear/kurta set/kurta3.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 19,
        "name": "kurta four",
        "price": 1500,
        "color": "green",
        "type": "kurta & festive wear",
        "category": "men",
        "subCategory": "kurta set",
        "image": "men/Kurta & festive wear/kurta set/kurta4.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 20,
        "name": "kurta five",
        "price": 1700,
        "color": "green",
        "type": "kurta & festive wear",
        "category": "men",
        "subCategory": "kurta set",
        "image": "men/Kurta & festive wear/kurta set/kurta5.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 21,
        "name": "jacket one",
        "price": 2000,
        "color": "blue",
        "type": "kurta & festive wear",
        "category": "men",
        "subCategory": "nehru jackets",
        "image": "men/Kurta & festive wear/Nehru jackets/jacket1.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 22,
        "name": "jacket two",
        "price": 2200,
        "color": "blue",
        "type": "kurta & festive wear",
        "category": "men",
        "subCategory": "nehru jackets",
        "image": "men/Kurta & festive wear/Nehru jackets/jacket2.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 23,
        "name": "jacket three",
        "price": 2400,
        "color": "blue",
        "type": "kurta & festive wear",
        "category": "men",
        "subCategory": "nehru jackets",
        "image": "men/Kurta & festive wear/Nehru jackets/jacket3.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 24,
        "name": "jacket four",
        "price": 2200,
        "color": "blue",
        "type": "kurta & festive wear",
        "category": "men",
        "subCategory": "nehru jackets",
        "image": "men/Kurta & festive wear/Nehru jackets/jacket4.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 25,
        "name": "jacket five",
        "price": 2000,
        "color": "blue",
        "type": "kurta & festive wear",
        "category": "men",
        "subCategory": "nehru jackets",
        "image": "men/Kurta & festive wear/Nehru jackets/jacket5.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 26,
        "name": "sherwani one",
        "price": 1000,
        "color": "black",
        "type": "kurta & festive wear",
        "category": "men",
        "subCategory": "sherwani",
        "image": "men/Kurta & festive wear/sherwani/sherwani1.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 27,
        "name": "sherwani two",
        "price": 1500,
        "color": "black",
        "type": "kurta & festive wear",
        "category": "men",
        "subCategory": "sherwani",
        "image": "men/Kurta & festive wear/sherwani/sherwani2.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 28,
        "name": "sherwani three",
        "price": 1800,
        "color": "black",
        "type": "kurta & festive wear",
        "category": "men",
        "subCategory": "sherwani",
        "image": "men/Kurta & festive wear/sherwani/sherwani3.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 29,
        "name": "sherwani four",
        "price": 2000,
        "color": "black",
        "type": "kurta & festive wear",
        "category": "men",
        "subCategory": "sherwani",
        "image": "men/Kurta & festive wear/sherwani/sherwani4.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 30,
        "name": "sherwani five",
        "price": 2200,
        "color": "black",
        "type": "kurta & festive wear",
        "category": "men",
        "subCategory": "sherwani",
        "image": "men/Kurta & festive wear/sherwani/sherwani5.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 31,
        "name": "shirt one",
        "price": 500,
        "color": "white",
        "type": "Top wear",
        "category": "men",
        "subCategory": "casual shirts",
        "image": "men/Top wear/casual shirts/shirt1.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 32,
        "name": "shirt two",
        "price": 700,
        "color": "white",
        "type": "Top wear",
        "category": "men",
        "subCategory": "casual shirts",
        "image": "men/Top wear/casual shirts/shirt2.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 33,
        "name": "shirt three",
        "price": 800,
        "color": "white",
        "type": "Top wear",
        "category": "men",
        "subCategory": "casual shirts",
        "image": "men/Top wear/casual shirts/shirt3.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 34,
        "name": "shirt four",
        "price": 600,
        "color": "white",
        "type": "Top wear",
        "category": "men",
        "subCategory": "casual shirts",
        "image": "men/Top wear/casual shirts/shirt4.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 35,
        "name": "shirt five",
        "price": 900,
        "color": "white",
        "type": "Top wear",
        "category": "men",
        "subCategory": "casual shirts",
        "image": "men/Top wear/casual shirts/shirt5.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 36,
        "name": "shirt one",
        "price": 600,
        "color": "blue",
        "type": "Top wear",
        "category": "men",
        "subCategory": "formal shirts",
        "image": "men/Top wear/formal shirts/shirt1.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 37,
        "name": "shirt two",
        "price": 900,
        "color": "blue",
        "type": "Top wear",
        "category": "men",
        "subCategory": "formal shirts",
        "image": "men/Top wear/formal shirts/shirt2.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 38,
        "name": "shirt three",
        "price": 500,
        "color": "blue",
        "type": "Top wear",
        "category": "men",
        "subCategory": "formal shirts",
        "image": "men/Top wear/formal shirts/shirt3.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 39,
        "name": "shirt four",
        "price": 800,
        "color": "blue",
        "type": "Top wear",
        "category": "men",
        "subCategory": "formal shirts",
        "image": "men/Top wear/formal shirts/shirt4.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 40,
        "name": "shirt five",
        "price": 700,
        "color": "blue",
        "type": "Top wear",
        "category": "men",
        "subCategory": "formal shirts",
        "image": "men/Top wear/formal shirts/shirt5.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 41,
        "name": "shirt one",
        "price": 800,
        "color": "black",
        "type": "Top wear",
        "category": "men",
        "subCategory": "T-shirts",
        "image": "men/Top wear/T-shirt/shirt1.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 42,
        "name": "shirt two",
        "price": 1000,
        "color": "black",
        "type": "Top wear",
        "category": "men",
        "subCategory": "T-shirts",
        "image": "men/Top wear/T-shirt/shirt2.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 43,
        "name": "shirt three",
        "price": 900,
        "color": "black",
        "type": "Top wear",
        "category": "men",
        "subCategory": "T-shirts",
        "image": "men/Top wear/T-shirt/shirt3.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 44,
        "name": "shirt four",
        "price": 1100,
        "color": "black",
        "type": "Top wear",
        "category": "men",
        "subCategory": "T-shirts",
        "image": "men/Top wear/T-shirt/shirt4.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 45,
        "name": "shirt five",
        "price": 1300,
        "color": "black",
        "type": "Top wear",
        "category": "men",
        "subCategory": "T-shirts",
        "image": "men/Top wear/T-shirt/shirt5.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 46,
        "name": "jacket one",
        "price": 900,
        "color": "black",
        "type": "indian & fusion wear",
        "category": "women",
        "subCategory": "jackets",
        "image": "women/indian & fusion wear/jackets/jacket1.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 47,
        "name": "jacket two",
        "price": 1000,
        "color": "black",
        "type": "indian & fusion wear",
        "category": "women",
        "subCategory": "jackets",
        "image": "women/indian & fusion wear/jackets/jacket2.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 48,
        "name": "jacket three",
        "price": 1200,
        "color": "black",
        "type": "indian & fusion wear",
        "category": "women",
        "subCategory": "jackets",
        "image": "women/indian & fusion wear/jackets/jacket3.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 49,
        "name": "jacket four",
        "price": 1400,
        "color": "black",
        "type": "indian & fusion wear",
        "category": "women",
        "subCategory": "jackets",
        "image": "women/indian & fusion wear/jackets/jacket4.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 50,
        "name": "jacket five",
        "price": 1500,
        "color": "black",
        "type": "indian & fusion wear",
        "category": "women",
        "subCategory": "jackets",
        "image": "women/indian & fusion wear/jackets/jacket5.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 51,
        "name": "kurta one",
        "price": 700,
        "color": "red",
        "type": "indian & fusion wear",
        "category": "women",
        "subCategory": "kurtas & suits",
        "image": "women/indian & fusion wear/kurtas & suits/kurta5.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 52,
        "name": "kurta two",
        "price": 900,
        "color": "red",
        "type": "indian & fusion wear",
        "category": "women",
        "subCategory": "kurtas & suits",
        "image": "women/indian & fusion wear/kurtas & suits/kurta2.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 53,
        "name": "kurta three",
        "price": 1000,
        "color": "red",
        "type": "indian & fusion wear",
        "category": "women",
        "subCategory": "kurtas & suits",
        "image": "women/indian & fusion wear/kurtas & suits/kurta3.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 54,
        "name": "kurta four",
        "price": 1300,
        "color": "red",
        "type": "indian & fusion wear",
        "category": "women",
        "subCategory": "kurtas & suits",
        "image": "women/indian & fusion wear/kurtas & suits/kurta4.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 55,
        "name": "kurta five",
        "price": 1500,
        "color": "red",
        "type": "indian & fusion wear",
        "category": "women",
        "subCategory": "kurtas & suits",
        "image": "women/indian & fusion wear/kurtas & suits/kurta5.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 56,
        "name": "saree one",
        "price": 2000,
        "color": "green",
        "type": "indian & fusion wear",
        "category": "women",
        "subCategory": "Sarees",
        "image": "women/indian & fusion wear/Sarees/saree1.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 57,
        "name": "saree two",
        "price": 2800,
        "color": "red",
        "type": "indian & fusion wear",
        "category": "women",
        "subCategory": "Sarees",
        "image": "women/indian & fusion wear/Sarees/saree2.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 58,
        "name": "saree three",
        "price": 3000,
        "color": "red",
        "type": "indian & fusion wear",
        "category": "women",
        "subCategory": "Sarees",
        "image": "women/indian & fusion wear/Sarees/saree3.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 59,
        "name": "saree four",
        "price": 3200,
        "color": "red",
        "type": "indian & fusion wear",
        "category": "women",
        "subCategory": "Sarees",
        "image": "women/indian & fusion wear/Sarees/saree4.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 60,
        "name": "saree five",
        "price": 3400,
        "color": "red",
        "type": "indian & fusion wear",
        "category": "women",
        "subCategory": "Sarees",
        "image": "women/indian & fusion wear/Sarees/saree5.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 61,
        "name": "top one",
        "price": 800,
        "color": "blue",
        "type": "indian & fusion wear",
        "category": "women",
        "subCategory": "Tunics tops",
        "image": "women/indian & fusion wear/Tunics tops/top1.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 62,
        "name": "top two",
        "price": 700,
        "color": "blue",
        "type": "indian & fusion wear",
        "category": "women",
        "subCategory": "Tunics tops",
        "image": "women/indian & fusion wear/Tunics tops/top2.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 63,
        "name": "top three",
        "price": 1000,
        "color": "blue",
        "type": "indian & fusion wear",
        "category": "women",
        "subCategory": "Tunics tops",
        "image": "women/indian & fusion wear/Tunics tops/top3.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 64,
        "name": "top four",
        "price": 1300,
        "color": "blue",
        "type": "indian & fusion wear",
        "category": "women",
        "subCategory": "Tunics tops",
        "image": "women/indian & fusion wear/Tunics tops/top4.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 65,
        "name": "top five",
        "price": 1600,
        "color": "blue",
        "type": "indian & fusion wear",
        "category": "women",
        "subCategory": "Tunics tops",
        "image": "women/indian & fusion wear/Tunics tops/top5.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 66,
        "name": "dress one",
        "price": 1500,
        "color": "white",
        "type": "western wear",
        "category": "women",
        "subCategory": "dresses",
        "image": "women/western wear/dresses/dress1.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 67,
        "name": "dress two",
        "price": 1900,
        "color": "white",
        "type": "western wear",
        "category": "women",
        "subCategory": "dresses",
        "image": "women/western wear/dresses/dress2.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 68,
        "name": "dress three",
        "price": 2000,
        "color": "white",
        "type": "western wear",
        "category": "women",
        "subCategory": "dresses",
        "image": "women/western wear/dresses/dress3.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 69,
        "name": "dress four",
        "price": 2200,
        "color": "white",
        "type": "western wear",
        "category": "women",
        "subCategory": "dresses",
        "image": "women/western wear/dresses/dress4.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 70,
        "name": "dress five",
        "price": 2400,
        "color": "white",
        "type": "western wear",
        "category": "women",
        "subCategory": "dresses",
        "image": "women/western wear/dresses/dress5.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 71,
        "name": "jeans one",
        "price": 2400,
        "color": "blue",
        "type": "western wear",
        "category": "women",
        "subCategory": "jeans",
        "image": "women/western wear/jeans/jeans1.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 72,
        "name": "jeans two",
        "price": 2800,
        "color": "blue",
        "type": "western wear",
        "category": "women",
        "subCategory": "jeans",
        "image": "women/western wear/jeans/jeans2.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 73,
        "name": "jeans three",
        "price": 3000,
        "color": "blue",
        "type": "western wear",
        "category": "women",
        "subCategory": "jeans",
        "image": "women/western wear/jeans/jeans3.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 74,
        "name": "jeans four",
        "price": 3400,
        "color": "blue",
        "type": "western wear",
        "category": "women",
        "subCategory": "jeans",
        "image": "women/western wear/jeans/jeans4.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 75,
        "name": "jeans five",
        "price": 3700,
        "color": "blue",
        "type": "western wear",
        "category": "women",
        "subCategory": "jeans",
        "image": "women/western wear/jeans/jeans5.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 76,
        "name": "shirt one",
        "price": 600,
        "color": "black",
        "type": "western wear",
        "category": "women",
        "subCategory": "t-shirts",
        "image": "women/western wear/t-shits/shirt1.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 77,
        "name": "shirt two",
        "price": 900,
        "color": "black",
        "type": "western wear",
        "category": "women",
        "subCategory": "t-shirts",
        "image": "women/western wear/t-shits/shirt2.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 78,
        "name": "shirt three",
        "price": 1000,
        "color": "black",
        "type": "western wear",
        "category": "women",
        "subCategory": "t-shirts",
        "image": "women/western wear/t-shits/shirt3.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 79,
        "name": "shirt four",
        "price": 1400,
        "color": "black",
        "type": "western wear",
        "category": "women",
        "subCategory": "t-shirts",
        "image": "women/western wear/t-shits/shirt4.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 80,
        "name": "shirt five",
        "price": 1600,
        "color": "black",
        "type": "western wear",
        "category": "women",
        "subCategory": "t-shirts",
        "image": "women/western wear/t-shits/shirt5.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 81,
        "name": "top one",
        "price": 500,
        "color": "red",
        "type": "western wear",
        "category": "women",
        "subCategory": "tops",
        "image": "women/western wear/tops/top1.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 82,
        "name": "top two",
        "price": 700,
        "color": "red",
        "type": "western wear",
        "category": "women",
        "subCategory": "tops",
        "image": "women/western wear/tops/top2.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 83,
        "name": "top three",
        "price": 900,
        "color": "red",
        "type": "western wear",
        "category": "women",
        "subCategory": "tops",
        "image": "women/western wear/tops/top3.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 84,
        "name": "top four",
        "price": 1100,
        "color": "red",
        "type": "western wear",
        "category": "women",
        "subCategory": "tops",
        "image": "women/western wear/tops/top4.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 85,
        "name": "top five",
        "price": 1300,
        "color": "red",
        "type": "western wear",
        "category": "women",
        "subCategory": "tops",
        "image": "women/western wear/tops/top5.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 86,
        "name": "trouser one",
        "price": 1000,
        "color": "white",
        "type": "western wear",
        "category": "women",
        "subCategory": "trousers",
        "image": "women/western wear/trousers/trouser1.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 87,
        "name": "trouser two",
        "price": 1500,
        "color": "white",
        "type": "western wear",
        "category": "women",
        "subCategory": "trousers",
        "image": "women/western wear/trousers/trouser2.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 88,
        "name": "trouser three",
        "price": 1800,
        "color": "white",
        "type": "western wear",
        "category": "women",
        "subCategory": "trousers",
        "image": "women/western wear/trousers/trouser3.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 89,
        "name": "trouser four",
        "price": 2000,
        "color": "white",
        "type": "western wear",
        "category": "women",
        "subCategory": "trousers",
        "image": "women/western wear/trousers/trouser4.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 90,
        "name": "trouser five",
        "price": 2400,
        "color": "white",
        "type": "western wear",
        "category": "women",
        "subCategory": "trousers",
        "image": "women/western wear/trousers/trouser5.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 91,
        "name": "jacket one",
        "price": 1000,
        "color": "red",
        "type": "boys clothing",
        "category": "kids",
        "subCategory": "jackets",
        "image": "kids/boys clothing/jackets/jacket1.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 92,
        "name": "jacket two",
        "price": 2000,
        "color": "red",
        "type": "boys clothing",
        "category": "kids",
        "subCategory": "jackets",
        "image": "kids/boys clothing/jackets/jacket2.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 93,
        "name": "jacket three",
        "price": 2600,
        "color": "red",
        "type": "boys clothing",
        "category": "kids",
        "subCategory": "jackets",
        "image": "kids/boys clothing/jackets/jacket3.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 94,
        "name": "jacket four",
        "price": 2900,
        "color": "red",
        "type": "boys clothing",
        "category": "kids",
        "subCategory": "jackets",
        "image": "kids/boys clothing/jackets/jacket4.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 95,
        "name": "jacket five",
        "price": 3200,
        "color": "red",
        "type": "boys clothing",
        "category": "kids",
        "subCategory": "jackets",
        "image": "kids/boys clothing/jackets/jacket5.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 96,
        "name": "jeans one",
        "price": 2400,
        "color": "white",
        "type": "boys clothing",
        "category": "kids",
        "subCategory": "jeans",
        "image": "kids/boys clothing/jeans/jeans1.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 97,
        "name": "jeans two",
        "price": 3000,
        "color": "white",
        "type": "boys clothing",
        "category": "kids",
        "subCategory": "jeans",
        "image": "kids/boys clothing/jeans/jeans2.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 98,
        "name": "jeans three",
        "price": 3200,
        "color": "white",
        "type": "boys clothing",
        "category": "kids",
        "subCategory": "jeans",
        "image": "kids/boys clothing/jeans/jeans3.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 99,
        "name": "jeans four",
        "price": 3400,
        "color": "white",
        "type": "boys clothing",
        "category": "kids",
        "subCategory": "jeans",
        "image": "kids/boys clothing/jeans/jeans4.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 100,
        "name": "jeans five",
        "price": 3900,
        "color": "white",
        "type": "boys clothing",
        "category": "kids",
        "subCategory": "jeans",
        "image": "kids/boys clothing/jeans/jeans5.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 101,
        "name": "party wear one",
        "price": 2600,
        "color": "green",
        "type": "boys clothing",
        "category": "kids",
        "subCategory": "party wear",
        "image": "kids/boys clothing/party wear/party wear1.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 102,
        "name": "party wear two",
        "price": 2800,
        "color": "green",
        "type": "boys clothing",
        "category": "kids",
        "subCategory": "party wear",
        "image": "kids/boys clothing/party wear/party wear2.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 103,
        "name": "party wear three",
        "price": 3000,
        "color": "green",
        "type": "boys clothing",
        "category": "kids",
        "subCategory": "party wear",
        "image": "kids/boys clothing/party wear/party wear3.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 104,
        "name": "party wear four",
        "price": 3300,
        "color": "green",
        "type": "boys clothing",
        "category": "kids",
        "subCategory": "party wear",
        "image": "kids/boys clothing/party wear/party wear4.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 105,
        "name": "party wear five",
        "price": 3600,
        "color": "green",
        "type": "boys clothing",
        "category": "kids",
        "subCategory": "party wear",
        "image": "kids/boys clothing/party wear/party wear5.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 106,
        "name": "shirt one",
        "price": 1500,
        "color": "blue",
        "type": "boys clothing",
        "category": "kids",
        "subCategory": "shirts",
        "image": "kids/boys clothing/shirts/shirt1.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 107,
        "name": "shirt two",
        "price": 1800,
        "color": "blue",
        "type": "boys clothing",
        "category": "kids",
        "subCategory": "shirts",
        "image": "kids/boys clothing/shirts/shirt2.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 108,
        "name": "shirt three",
        "price": 2000,
        "color": "blue",
        "type": "boys clothing",
        "category": "kids",
        "subCategory": "shirts",
        "image": "kids/boys clothing/shirts/shirt3.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 109,
        "name": "shirt four",
        "price": 2400,
        "color": "blue",
        "type": "boys clothing",
        "category": "kids",
        "subCategory": "shirts",
        "image": "kids/boys clothing/shirts/shirt4.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 110,
        "name": "shirt five",
        "price": 2700,
        "color": "blue",
        "type": "boys clothing",
        "category": "kids",
        "subCategory": "shirts",
        "image": "kids/boys clothing/shirts/shirt5.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 111,
        "name": "t-shirt one",
        "price": 2500,
        "color": "black",
        "type": "boys clothing",
        "category": "kids",
        "subCategory": "party wear",
        "image": "kids/boys clothing/t-shirts/shirt1.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 112,
        "name": "t-shirt two",
        "price": 2700,
        "color": "black",
        "type": "boys clothing",
        "category": "kids",
        "subCategory": "party wear",
        "image": "kids/boys clothing/t-shirts/shirt2.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 113,
        "name": "t-shirt three",
        "price": 3000,
        "color": "black",
        "type": "boys clothing",
        "category": "kids",
        "subCategory": "party wear",
        "image": "kids/boys clothing/t-shirts/shirt3.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 114,
        "name": "t-shirt four",
        "price": 3700,
        "color": "black",
        "type": "boys clothing",
        "category": "kids",
        "subCategory": "party wear",
        "image": "kids/boys clothing/t-shirts/shirt4.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 115,
        "name": "t-shirt five",
        "price": 4000,
        "color": "black",
        "type": "boys clothing",
        "category": "kids",
        "subCategory": "party wear",
        "image": "kids/boys clothing/t-shirts/shirt5.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 116,
        "name": "trouser one",
        "price": 3000,
        "color": "black",
        "type": "boys clothing",
        "category": "kids",
        "subCategory": "trouser",
        "image": "kids/boys clothing/trouser/trouser1.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 117,
        "name": "trouser two",
        "price": 3400,
        "color": "black",
        "type": "boys clothing",
        "category": "kids",
        "subCategory": "trouser",
        "image": "kids/boys clothing/trouser/trouser2.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 118,
        "name": "trouser three",
        "price": 3700,
        "color": "black",
        "type": "boys clothing",
        "category": "kids",
        "subCategory": "trouser",
        "image": "kids/boys clothing/trouser/trouser3.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 119,
        "name": "trouser four",
        "price": 3900,
        "color": "black",
        "type": "boys clothing",
        "category": "kids",
        "subCategory": "trouser",
        "image": "kids/boys clothing/trouser/trouser4.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 120,
        "name": "trouser five",
        "price": 3200,
        "color": "black",
        "type": "boys clothing",
        "category": "kids",
        "subCategory": "trouser",
        "image": "kids/boys clothing/trouser/trouser5.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 121,
        "name": "dress one",
        "price": 2700,
        "color": "blue",
        "type": "girls clothing",
        "category": "kids",
        "subCategory": "dresses",
        "image": "kids/girls clothing/dresses/dress1.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 122,
        "name": "dress two",
        "price": 2900,
        "color": "blue",
        "type": "girls clothing",
        "category": "kids",
        "subCategory": "dresses",
        "image": "kids/girls clothing/dresses/dress2.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 123,
        "name": "dress three",
        "price": 3000,
        "color": "blue",
        "type": "girls clothing",
        "category": "kids",
        "subCategory": "dresses",
        "image": "kids/girls clothing/dresses/dress3.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 124,
        "name": "dress four",
        "price": 3500,
        "color": "blue",
        "type": "girls clothing",
        "category": "kids",
        "subCategory": "dresses",
        "image": "kids/girls clothing/dresses/dress4.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 125,
        "name": "dress five",
        "price": 4000,
        "color": "blue",
        "type": "girls clothing",
        "category": "kids",
        "subCategory": "dresses",
        "image": "kids/girls clothing/dresses/dress5.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 126,
        "name": "kurta one",
        "price": 3000,
        "color": "red",
        "type": "girls clothing",
        "category": "kids",
        "subCategory": "kurta set",
        "image": "kids/girls clothing/kurta set/kurta1.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 127,
        "name": "kurta two",
        "price": 3600,
        "color": "red",
        "type": "girls clothing",
        "category": "kids",
        "subCategory": "kurta set",
        "image": "kids/girls clothing/kurta set/kurta2.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 128,
        "name": "kurta three",
        "price": 3900,
        "color": "red",
        "type": "girls clothing",
        "category": "kids",
        "subCategory": "kurta set",
        "image": "kids/girls clothing/kurta set/kurta3.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 129,
        "name": "kurta four",
        "price": 4000,
        "color": "red",
        "type": "girls clothing",
        "category": "kids",
        "subCategory": "kurta set",
        "image": "kids/girls clothing/kurta set/kurta4.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 130,
        "name": "kurta five",
        "price": 4600,
        "color": "red",
        "type": "girls clothing",
        "category": "kids",
        "subCategory": "kurta set",
        "image": "kids/girls clothing/kurta set/kurta5.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 131,
        "name": "top one",
        "price": 2000,
        "color": "black",
        "type": "girls clothing",
        "category": "kids",
        "subCategory": "tops",
        "image": "kids/girls clothing/tops/top1.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 132,
        "name": "top two",
        "price": 2400,
        "color": "black",
        "type": "girls clothing",
        "category": "kids",
        "subCategory": "tops",
        "image": "kids/girls clothing/tops/top2.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 133,
        "name": "top three",
        "price": 2700,
        "color": "black",
        "type": "girls clothing",
        "category": "kids",
        "subCategory": "tops",
        "image": "kids/girls clothing/tops/top3.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 134,
        "name": "top four",
        "price": 3000,
        "color": "black",
        "type": "girls clothing",
        "category": "kids",
        "subCategory": "tops",
        "image": "kids/girls clothing/tops/top4.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 135,
        "name": "top five",
        "price": 3200,
        "color": "black",
        "type": "girls clothing",
        "category": "kids",
        "subCategory": "tops",
        "image": "kids/girls clothing/tops/top5.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 136,
        "name": "shirt one",
        "price": 3000,
        "color": "green",
        "type": "top wear",
        "category": "men",
        "subCategory": "sweat shirts",
        "image": "men/Top wear/sweat shirts/shirt1.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 137,
        "name": "shirt two",
        "price": 3400,
        "color": "green",
        "type": "top wear",
        "category": "men",
        "subCategory": "sweat shirts",
        "image": "men/Top wear/sweat shirts/shirt2.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 138,
        "name": "shirt three",
        "price": 3900,
        "color": "green",
        "type": "top wear",
        "category": "men",
        "subCategory": "sweat shirts",
        "image": "men/Top wear/sweat shirts/shirt3.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 139,
        "name": "shirt four",
        "price": 4000,
        "color": "green",
        "type": "top wear",
        "category": "men",
        "subCategory": "sweat shirts",
        "image": "men/Top wear/sweat shirts/shirt4.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 140,
        "name": "shirt five",
        "price": 4400,
        "color": "green",
        "type": "top wear",
        "category": "men",
        "subCategory": "sweat shirts",
        "image": "men/Top wear/sweat shirts/shirt5.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 141,
        "name": "kurta one",
        "price": 3000,
        "color": "red",
        "type": "indian & fusion wear",
        "category": "women",
        "subCategory": "kurta & suits",
        "image": "women/indian & fusion wear/kurtas & suits/kurti1.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 142,
        "name": "kurta two",
        "price": 3600,
        "color": "red",
        "type": "indian & fusion wear",
        "category": "women",
        "subCategory": "kurta & suits",
        "image": "women/indian & fusion wear/kurtas & suits/kurta2.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 143,
        "name": "kurta three",
        "price": 3900,
        "color": "red",
        "type": "indian & fusion wear",
        "category": "women",
        "subCategory": "kurta & suits",
        "image": "women/indian & fusion wear/kurtas & suits/kurta3.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 144,
        "name": "kurta four",
        "price": 4400,
        "color": "red",
        "type": "indian & fusion wear",
        "category": "women",
        "subCategory": "kurta & suits",
        "image": "women/indian & fusion wear/kurtas & suits/kurta4.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    },
    {
        "id": 145,
        "name": "kurta five",
        "price": 4900,
        "color": "red",
        "type": "indian & fusion wear",
        "category": "women",
        "subCategory": "kurta & suits",
        "image": "women/indian & fusion wear/kurtas & suits/kurta5.webp",
        "quantity": 10,
        "available": true,
        "addToBag": false,
        "wishList": false
    }
]

export default data;